#!/usr/bin/env node
/**
 * prod_deploy — Swipick release script (the only sanctioned way to ship).
 *
 * Flow:
 *   1. Preflight     — on dev, clean tree, fetch tags; verify prod is an ancestor of HEAD; warn on unpushed dev commits
 *   2. Version prompt — highest v* tag -> patch+1 suggestion -> semver gt check
 *   3. Build validate — npm run build (abort on failure)
 *   4. Version bump   — package.json (+ synced lockfile) + CHANGELOG.md + src/version.ts, commit on dev
 *   5. Tag + promote  — git tag vX.Y.Z ; fast-forward prod via `git push origin dev:prod`
 *   6. Push           — dev + tag (the tag triggers pages.yml and release.yml)
 *
 * Flags: --dry-run  Stop after the version prompt; change nothing.
 */
import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { createInterface } from 'node:readline'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const DRY_RUN = process.argv.includes('--dry-run')
const PAGES_URL = 'https://kepes.github.io/swipick/'
const RELEASES_URL = 'https://github.com/kepes/swipick/releases'

const c = { reset: '\x1b[0m', bold: '\x1b[1m', red: '\x1b[31m', green: '\x1b[32m', yellow: '\x1b[33m', cyan: '\x1b[36m' }
const log = {
  info: (m) => console.log(`${c.cyan}[info]${c.reset} ${m}`),
  ok: (m) => console.log(`${c.green}[ok]${c.reset} ${m}`),
  warn: (m) => console.log(`${c.yellow}[warn]${c.reset} ${m}`),
  err: (m) => console.error(`${c.red}[error]${c.reset} ${m}`),
}
function abort(m) { log.err(m); process.exit(1) }
function exec(cmd, opts = {}) {
  return execSync(cmd, { cwd: ROOT, encoding: 'utf8', stdio: opts.silent ? 'pipe' : 'inherit' })?.toString().trim() ?? ''
}
function execSilent(cmd) { try { return exec(cmd, { silent: true }) } catch { return '' } }
function ask(q) {
  const rl = createInterface({ input: process.stdin, output: process.stdout })
  return new Promise((r) => rl.question(`${c.yellow}?${c.reset} ${q} `, (a) => { rl.close(); r(a.trim()) }))
}

function parseVersion(s) {
  const m = String(s ?? '').match(/^v?(\d+)\.(\d+)\.(\d+)$/)
  return m ? { major: +m[1], minor: +m[2], patch: +m[3] } : null
}
function fmt(v) { return `${v.major}.${v.minor}.${v.patch}` }
function gt(a, b) {
  if (a.major !== b.major) return a.major > b.major
  if (a.minor !== b.minor) return a.minor > b.minor
  return a.patch > b.patch
}
function latestTag() {
  let best = null
  for (const t of execSilent('git tag --list "v*"').split('\n').filter(Boolean)) {
    const v = parseVersion(t)
    if (v && (!best || gt(v, best.version))) best = { version: v, tag: t }
  }
  return best
}
function todayISO() {
  const d = new Date()
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
}

function writeVersionFile(version, commit) {
  const content =
    `// AUTO-GENERATED by scripts/prod-deploy.mjs — do NOT edit manually.\n` +
    `// Checked in with 'dev'; overwritten with the real version at each release.\n` +
    `export const VERSION = '${version}'\n` +
    `export const COMMIT_HASH = '${commit}'\n` +
    `export const BUILD_AT = '${new Date().toISOString()}'\n`
  writeFileSync(path.join(ROOT, 'src/version.ts'), content)
}
function bumpPackageJson(version) {
  const p = path.join(ROOT, 'package.json')
  const pkg = JSON.parse(readFileSync(p, 'utf8'))
  pkg.version = version
  writeFileSync(p, JSON.stringify(pkg, null, 2) + '\n')
}
function updateChangelog(tag) {
  const p = path.join(ROOT, 'CHANGELOG.md')
  const cl = readFileSync(p, 'utf8')
  writeFileSync(p, cl.replace(/^## \[Unreleased\]/m, `## [Unreleased]\n\n## [${tag}] - ${todayISO()}`))
}

async function main() {
  // Step 1: preflight
  const branch = execSilent('git branch --show-current')
  if (branch !== 'dev') abort(`Run from 'dev' (current: '${branch || 'detached'}').`)
  if (execSilent('git status --porcelain')) abort('Working tree not clean — commit or stash first.')
  exec('git fetch origin --tags', { silent: true })
  // prod must be an ancestor of the commit we release, or the fast-forward `git push origin dev:prod` is rejected.
  try { exec('git merge-base --is-ancestor origin/prod HEAD', { silent: true }) }
  catch { abort('origin/prod is not an ancestor of HEAD — the prod fast-forward would be rejected. Reconcile prod first.') }
  const unpushed = execSilent('git log origin/dev..dev --oneline')
  if (unpushed) {
    log.warn('Unpushed commits on dev (they WILL be released):')
    console.log(unpushed)
  }

  // Step 2: version prompt
  const latest = latestTag()
  const current = latest?.version ?? { major: 0, minor: 0, patch: 0 }
  log.info(`Current version: ${latest?.tag ?? '(none)'}`)
  const suggested = { ...current, patch: current.patch + 1 }
  const input = await ask(`New version [${fmt(suggested)}]:`)
  const next = input ? parseVersion(input) : suggested
  if (!next) abort(`Invalid version '${input}'. Expected X.Y.Z`)
  if (!gt(next, current)) abort(`New version must be greater than ${fmt(current)}`)
  const version = fmt(next)
  const tag = `v${version}`
  if (execSilent('git tag --list').split('\n').includes(tag)) abort(`Tag ${tag} already exists`)

  console.log(`\n  ${latest?.tag ?? '—'} -> ${c.bold}${tag}${c.reset}\n`)
  if (DRY_RUN) { log.info('--dry-run: stopping, nothing changed.'); process.exit(0) }
  if ((await ask('Proceed? (y/n)')).toLowerCase() !== 'y') { log.info('Aborted.'); process.exit(0) }

  // Step 3: build validation
  log.info('npm run build…')
  try { exec('npm run build') } catch { abort('Build failed — fix on dev, then retry.') }

  // Step 4: version artifacts + commit
  const commit = execSilent('git rev-parse --short HEAD')
  writeVersionFile(version, commit)
  bumpPackageJson(version)
  // Keep package-lock.json's version in sync with package.json, or the release commit
  // ships a desynced lockfile and every CI `npm ci` (pages.yml + release.yml) fails.
  exec('npm install --package-lock-only --no-audit', { silent: true })
  updateChangelog(tag)
  exec('git add package.json package-lock.json CHANGELOG.md src/version.ts', { silent: true })
  exec(`git commit -m "chore: release ${tag}"`, { silent: true })
  log.ok(`Committed release ${tag}`)

  // Step 5+6: tag, fast-forward prod, push.
  // Push prod first (the riskiest push): if it is rejected, dev and the tag are not yet pushed,
  // so no half-released state is left behind. The tag goes last — it is the CI trigger.
  exec(`git tag ${tag}`, { silent: true })
  try {
    log.info('git push origin dev:prod (fast-forward prod)…'); exec('git push origin dev:prod')
    log.info('git push origin dev…'); exec('git push origin dev')
    log.info(`git push origin ${tag}…`); exec(`git push origin ${tag}`)
  } catch (err) {
    // A push failed mid-sequence. The local release-commit and tag already exist, so a naive
    // re-run would abort at Step 2 with "Tag already exists". Point the operator at recovery
    // instead of silently leaving a half-released state. Recovery is NOT automated because the
    // correct action depends on which pushes already succeeded.
    log.err('Push failed mid-sequence — the remote may be partially updated.')
    log.err(`Inspect: git ls-remote origin refs/heads/prod refs/heads/dev refs/tags/${tag}`)
    log.err(`  • If NOTHING pushed: git tag -d ${tag} && git reset --hard HEAD~1, then re-run.`)
    log.err('  • If some pushes SUCCEEDED: do NOT reset — re-run only the missing git push commands, then push the tag.')
    throw err
  }

  console.log(`\n${c.green}${c.bold}Released ${tag}${c.reset} — GitHub Actions is building the web deploy + desktop binaries.`)
  console.log(`  Web:      ${PAGES_URL}`)
  console.log(`  Releases: ${RELEASES_URL}`)
}

main().catch((err) => {
  log.err(`Deploy failed: ${err?.message ?? err}`)
  process.exit(1)
})
