// AUTO-GENERATED by scripts/prod-deploy.mjs — do NOT edit manually.
// Checked in with 'dev'; overwritten with the real version at each release.
export const VERSION = 'dev'
export const COMMIT_HASH = 'dev'
export const BUILD_AT = ''
