// AUTO-GENERATED by scripts/prod-deploy.mjs — do NOT edit manually.
// Checked in with 'dev'; overwritten with the real version at each release.
export const VERSION = '1.1.0'
export const COMMIT_HASH = '3491754'
export const BUILD_AT = '2026-07-13T11:06:37.623Z'
